name = "Reveal Positions"
version = 2
description = "Reveals starting locations of players"
author = "Myxir, CookieNoob"
url = ""
uid = "b0d9ac94-c5o6-11e5-9s12-bf0be0483c18"
exclusive = false
ui_only = true
conflicts = {}
